### ISSUE TITLE
Velocity support

### ISSUE THREAD

**Issue by joshwenke** [Winds-Studio/DeathMessages#116]
Please allow the plugin to work with Velocity, not just BungeeCord!

**Comment by Dreeam-qwq** [comment]
DeathMessages already works fine on Velocity, since Velocity supprts Bungee message channel messaging. You can check https://docs.papermc.io/velocity/dev/plugin-messaging#bungeecord-channel-compatibility, enable `bungee-plugin-message-channel` in velocity config, and config DeathMessages's bungee settings exactly same as using BungeeCord / Waterfall
